- name: ansible play to create ec instances and dns records
  hosts: local
  connection: local
  vars:
    sg_id: sg-093f7b0430f683d14
    ami_id: ami-09c813fb71547fc4f
    dns: rscloudservices.icu
    instances:
     - mongodb
     - catalogue
     - frontend
     - redis
     - rabbitm
     - user
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: t3.micro
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
    - name: print public_ip
      ansible.builtin.debug:
        msg: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_output.results }}"
    - name: print private.IPs
      ansible.builtin.debug:
        msg: "{{ item.private_ip_address }}"
      loop: "{{ ec2_output.results | map(attribute='instances') | flatten }}"
    - name: create dns records for private_ips
      amazon.aws.route53:
        state: present
        zone: "{{ dns }}"
        record: "{{ item.item}}.{{ dns }}"
        type: A
        ttl: 1
        overwrite: true
        value: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_output.results }}"
    - name: create dns records from frontend
      amazon.aws.route53:
        state: present
        zone: "{{ dns }}"
        record: "{{ dns }}"
        type: A
        ttl: 1
        overwrite: true
        value: "{{ item.instances[0].public_ip_address }}"
      when: item.item == "frontend"
      loop: "{{ ec2_output.results }}"