- name: creating ec2-instances using ansible
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-093f7b0430f683d14
    vpc_id: vpc-0300f76b9ebd56688
    instances:
      - mongodb
      - redis
  tasks:
  - name: creating ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      instance_type: t3.micro
      tags:
       Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_data
  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_data }}"
