- name: ansible play to create ec instances and dns records
  hosts: local
  connection: local
  vars:
    sg_id: sg-093f7b0430f683d14
    ami_id: ami-09c813fb71547fc4f
    instances:
     - mongodb
     - rabbitmq
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: t3.micro
        tags:
          - Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
    - name: print public_ip
      ansible.builtin.debug:
        msg: "{{ item.instances[0].public_ip }}"
      loop: "{{ ec2_output.results }}"
    - name: print private.IPs
      ansible.builtin.debug:
        msg: "{{ item.private_ip }}"
      loop: "{{ ec2_output.results | map(attribute='instances') | flatten }}"