- name: cart configuration
  hosts: cart
  become: yes
  tasks:
   - name: disable default version nodejs
     ansible.builtin.command: dnf module disable nodejs -y
    
   - name: enable required version nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.dnf:
       name: nodejs
       state: present

   - name: create system-user
     ansible.builtin.user:
       name: roboshop
       comment: roboshop system cart
       create_home: yes

   - name: create directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download code
     ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
       dest: /app
       remote_src: yes

   - name: install dependencies
     community.general.npm:
       path: /app

   - name: create cart service
     ansible.builtin.copy:
       src: cart.service
       dest: /etc/systemd/system/cart.service

   - name: daemon reload
     ansible.builtin.systemd:
       daemon_reload: yes

   - name: start and enable cart
     ansible.builtin.service:
       name: cart
       state: started
       enabled: yes