- name: configuring catalogue server
  hosts: catalogue
  become: true
  tasks:
   - name: remove default nodejs
     ansible.builtin.command:
       cmd: dnf module disable nodejs -y

   - name: enable required nodejs version
     ansible.builtin.command:
       cmd: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.dnf:
       name: nodejs
       state: present

   - name: Create roboshop user with nologin
     ansible.builtin.user:
       name: roboshop
       create_home: yes
       shell: /sbin/nologin
       comment: roboshop system user
   - name: Recursively change ownership of a directory
     ansible.builtin.file:
       path: /app
       state: directory
