- name: configuring catalogue server
  hosts: catalogue
  become: true
  tasks:
   - name: remove default nodejs
     ansible.builtin.command:
       cmd: dnf module disable nodejs -y

   - name: enable required nodejs version
     ansible.builtin.command:
       cmd: dnf module enable nodejs:20 -y

   - name: copy repo
     ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

   - name: install nodejs
     ansible.builtin.dnf:
       name: "{{ item }}"
       state: present
     loop:
       - nodejs
       - mongodb-mongosh

   - name: Create roboshop user with nologin
     ansible.builtin.user:
       name: roboshop
       create_home: yes
       shell: /sbin/nologin
       comment: roboshop system user

   - name: Download and unzip a file
     ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /app/
      remote_src: yes   

   - name: create app directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: remove default nodejs
     ansible.builtin.command:
       cmd: npm install

   - name: copy service requirements
     ansible.builtin.copy:
       src: catalogue.service
       dest: /etc/systemd/system/catalogue.service
       
   - name: start and enable catalogue service
     ansible.builtin.service:
       name: catalogue
       state: started
       enabled: yes
       daemon-reload: true

   - name: load schemas into mongodb
     ansible.builtin.command:
       cmd: mongosh --host mongodb.rscloudservices.icu </app/db/master-data.js