- name: creating ec2_instance using ansible
  hosts: local
  connection: local
  vars:
    sg_id: sg-093f7b0430f683d14
    ami_id: ami-09c813fb71547fc4f
    hosted_zone: rscloudservices.icu
    hosted_zone_id: Z0711084A6IKM873A3LI
    instances:
      - mongodb
      - redis
  tasks:
    - name: create instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: t3.micro
        tags:
          Name: "{{ item }}"     
        loop: "{{ instances }}"
        register: ec2_output
    
    - name: print ec2_output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: create route53 records
      amazon.aws.route53:
        state: present
        zone_id: "{{ hosted_zone_id }}"
        zone: "{{ hosted_zone }}"
        record: "{{ item.item }}.{{ zone_id }}"
        type: A
        ttl: 1
        overwrite: true
      loop: "{{ ec2_output.results }}"