- name: creating ec2
  hosts: local
  connection: local
  become: true
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-093f7b0430f683d14
    tier: t3.micro
    instances:
      - mongodb
      - rabbitmq
  tasks:
    - name: create ecs
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
    - name: print ec2_output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"