- name: create aws servers
  hosts: local
  connection: local
  vars:
    sg_id: sg-093f7b0430f683d14
    ami_id: ami-09c813fb71547fc4f
    instances:
      - mongodb
      - rabbitmq
  tasks:
  - name: creating servers
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      instance_type: t3.micro
      security_groups: "{{ sg_id }}"
      region: us-east-1
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance_info

  - name: register ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_instance_info }}"

  - name: print public_ip
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address}}"
    loop: "{{ ec2_instance_info.results }}"