- name: dispatch configuration
  hosts: dispatch
  become: yes
  tasks:
   - name: install golang
     ansible.builtin.dnf:
       name: golang
       state: present

   - name: create system-user
     ansible.builtin.user:
       name: roboshop
       comment: roboshop system user
       create_home: yes

   - name: create directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download code
     ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip 
       dest: /app
       remote_src: yes
   - name: go to specific directory
     ansible.builtin.find:
     paths: /app
     file_type: directory  

   - name: dependencies go-mod
     ansible.builtin.shell: go mod init dispatch
     args:
       chdir: /app   

   - name: dependencies go-get
     ansible.builtin.shell: go get
     args:
       chdir: /app  

   - name: dependencies go-build
     ansible.builtin.shell: go build
     args:
       chdir: /app  

   - name: create user service
     ansible.builtin.copy:
       src: user.service
       dest: /etc/systemd/system/user.service

   - name: daemon reload
     ansible.builtin.systemd:
       daemon_reload: yes

   - name: start and enable user
     ansible.builtin.service:
       name: user
       state: started
       enabled: yes