- name: payment configuration
  hosts: payment
  become: yes
  tasks:
   - name: install python3 gcc python3-devel
     ansible.builtin.dnf:
       name: "{{ item }}"
       state: present
     loop:
       - python3
       - gcc
       - python3-devel

   - name: create system-user
     ansible.builtin.user:
       name: roboshop
       comment: roboshop system user
       create_home: yes

   - name: create directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download code
     ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
       dest: /app
       remote_src: yes

   - name: Install Python requirements using pip3
     ansible.builtin.pip:
       requirements: /app/requirements.txt

   - name: create payment service
     ansible.builtin.copy:
       src: payment.service
       dest: /etc/systemd/system/payment.service

   - name: daemon reload
     ansible.builtin.systemd:
       daemon_reload: yes

   - name: start and enable payment
     ansible.builtin.service:
       name: payment
       state: started
       enabled: yes