- name: user configuration
  hosts: user
  become: yes
  tasks:
   - name: disable default version nodejs
     ansible.builtin.command: dnf module disable nodejs -y
    
   - name: enable required version nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: install nodejs
     ansible.builtin.dnf:
       name: nodejs
       state: present

   - name: create system-user
     ansible.builtin.user:
       name: roboshop
       comment: roboshop system user
       create_home: yes

   - name: create directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download code
     ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
       dest: /app

   - name: install dependencies
     community.general.npm:
       path: /app

   - name: create user service
     ansible.builtin.copy:
       src: user.service
       dest: /etc/systemd/system/user.service

   - name: daemon reload
     ansible.builtin.service:
       name: user
       daemon-reload: yes
       status: started
       enabled: yes
