- name: How to use Gathering Facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "RedHat"